version: "2.0"

services:

  node:
    image: node:8-alpine
    volumes:
    - ./:/build

  dev:
    image: you/your-image-name:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
    - DEBUG=*
    - PORT=3000
    ports:
    - "3000:3000"
    volumes:
    - "./src:/app/src"
    - "./backpack.config.js:/app/backpack.config.js"
    - "./package.json:/app/package.json"
    - "./package-lock.json:/app/package-lock.json"
